name: BookSource
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.0
  json_annotation: ^4.0.1 #json数据生成实体类
  json_path: ^0.3.0
  html: ^0.15.0
  jsparser: ^2.0.1
  flutter_qjs: ^0.3.6
#  dartjsengine: ^1.0.1
#  expressions: ^0.2.3
#  xml: ^5.1.2
#  beautifulsoup: ^0.0.1 #不支持null safety
#  dart_json_mapper: ^2.1.2
#  path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
  build_runner: ^2.0.0
  json_serializable: ^4.0.1